name: textlinks
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/binkapS/textlinks

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
